### ISSUE TITLE
How to set chromedriver executable path in docker

### ISSUE THREAD

**Issue by as3379** [rafalf/docker-debian-selenium-headless#1]
Hi,

I'm trying to dockerize a python-selenium based project. But facing issue with passing chromedrive executable path. Please help me where am i going wrong.

**Test script code snip:**
class SeleniumClient(object):
    """
    A wrapper for selenium's client with various handy extensions.
    """
    def __init__(self, params=None, config="default", driver=None):
        if driver is not None:
            self.driver = driver
            return

        if params['location'] != "local":
            return

        root = os.path.dirname(os.path.realpath(__file__))
        self.logger.info("%s" , _platform)
        if _platform == "darwin":
            user = getpass.getuser()
            download_folder = "/Users/%s/downloads/" % user
        elif "win32" in _platform:
            user = getpass.getuser()
            download_folder = "/Users/%s/downloads/" % user
        elif "linux" in _platform:
            download_folder = "/var/lib/docker"
        else:
            raise NotImplemented("don't know where to save data")
        if "chrome" in config:
            options = webdriver.ChromeOptions()
            preferences = {
                "profile.default_content_settings.popups": 0,
                "download.default_directory": download_folder,
                "credentials_enable_service": 0,
                "profile.password_manager_enabled": 0
            }
            options.add_experimental_option("prefs", preferences)
            if config == "chrome":
                options.add_argument("--start-fullscreen")
            elif config == "chrome_headless":
                options.add_argument('--headless')
                options.add_argument('--disable-gpu')
                options.add_argument("--window-size=1920, 1200")

            self.driver = webdriver.Chrome(executable_path="app/drivers/chromedriver", options=options)
            self.driver.maximize_window()

Dockerfile: # Use an official Python runtime as a parent image
FROM python:3.7

ENV APP_DIR /app
WORKDIR $APP_DIR
ENV PYTHONPATH="$PYTHONPATH:/app"
ENV PYTHONUNBUFFERED="1"
ENV GUDB_ADMIN="UserXyzE123*"

# upgrade pip
RUN pip install --upgrade pip setuptools

COPY requirements.txt requirements.txt
COPY database database
COPY drivers drivers
COPY tests tests
COPY uits uits
COPY setup.py setup.py
COPY entrypoint.sh entrypoint.sh

#install required additional dependencies
RUN pip install -r requirements.txt

# install selenium
#RUN pip install selenium

# set display port to avoid crash
ENV DISPLAY=:99

RUN chmod +x entrypoint.sh

#ENTRYPOINT ["bash", "/app/entrypoint.sh"]

**Comment by rafalf** [comment]
if you copy it to /usr/local/bin, you'll not have to give it the path 
`COPY drivers/chromedriver /usr/local/bin`

`self.driver = webdriver.Chrome(options=options)`

**Comment by as3379** [comment]
Tried what you mentioned. Still facing the same error
